### ISSUE TITLE
Advice for changes in pabbrev?

### ISSUE THREAD

**Issue by clemera** [phillord/pabbrev#3]
Hi, 

I came across this package and I really like it. I prefer this against having a flickering popup while I'm writing, thank you so much for this!

I was playing around with it and because I did not expect to keep my changes I changed a bunch of things directly in the source without making commits or anything (bad me). Now I'm very pleased with the result (I incorporated flx matching for things near around point and in visible windows and made some interface changes, like using helm for selecting the alternatives, complete with double space instead of tab (only if a completion was shown before ), filter out completion candidates which complete less then three chars etc..

Would you be interested to incorporate some of this changes? Then I would try to clean up what I changed and split up the changes in smaller sized pull requests? Because that would be some work I thought I would better ask before I do this. Maybe I would need some help to properly include it and make the changes available via user options etc., because I'm not a professional.

Another option would be to release a new package like pabbrev+ or something like that, if that would be ok? But I think that is not a good idea because then I have to keep it in sync with your version. Otherwise the package seems to have reached a state where it does not change much anymore does it?

What do you think?

**Comment by phillord** [comment]
Thanks for the message and the interest.

So, first up, pabbrev is part of ELPA and, therefore, copyright assigned
to the FSF. I can only take patches if you have paperwork with FSF. I
can help you with the process if you do not know how, though.

Likewise, I need to depend directly only on things in ELPA -- Helm and
flx are not, I think, covered at the moment. So, we'd need to add this
as an add-on package. I wouldn't add helm completion as a default (I use
helm now, but did find it off-putting at first).

double-space instead of tab. I would like to make the completion key
more configurable, but I would not change the default. Getting that key
to work properly, though, has been fairly hard, so I'd need to convinced
of the implementation.

Do not show completion for less than three char completion, yes, that
would be good.

pabbrev+ as a place for Helm and flx sounds reasonable. I would not be
to worried about syncing; pabbrev is now old and mature. It does not
change much.

**Comment by clemera** [comment]
Sorry for the late reply. 

> I use helm now, but did find it off-putting at first

Same here, but after some adjustments I really started to like it, maybe my [guide](https://github.com/hatschipuh/helm-better-defaults) will be useful for you as well.

Given that flx and helm are not on elpa I should probably make an "extension" package  `pabbrev+` and put it on melpa. I will work on that, if it prooves useful enough over time. I have no paperwork with FSF but I would like to do that anyway. It is not really clear to me how it works. Do I have to assign the Copyright to every GNU program I contribute to? Or do I do it once for all GNU programs?

**Comment by phillord** [comment]
hatschipuh notifications@github.com writes:

> Sorry for the late reply. 
> 
> > I use helm now, but did find it off-putting at first
> 
> Same here, but after some adjustments it is really nice to use, maybe my
> [guide](https://github.com/hatschipuh/helm-better-defaults) will be useful to
> you.
> 
> I think now my changes are probably better packaged in a `pabbrev+` package on
> melpa. I will work on that. I have no paperwork with FSF but I would like to
> do that anyway. It is not really clear to me how it works. Do I have to assign
> the Copyright to every GNU program I contribute to? Or do I do it once for all
> GNU programs?

You can assign copyright for as many programs as you want.

If you send me an email, I can send you the details. It's not
complicated, although can take a while.

Phil

**Comment by clemera** [comment]
Thanks for your time, I will mail you if necessary. 

And by the way thank you for your contributions! I already learned a lot reading your answers on Stackexchange! Thanks!
