### ISSUE TITLE
Customizing the overlay

### ISSUE THREAD

**Issue by brongulus** [phillord/pabbrev#4]
Hi, thanks for the wonderful package, really enjoy using this over popup based completion systems.

I wanted to know if it's possible to change how the overlay appears, I don't want to see the "[" brackets and wanted to know if its possible to change the overlay without having to rewrite the entire `pabbrev-insert-suggestion` function and overriding the default with an advice, is it possible to just advise the `overlay-put` call?

And one more thing is the frequent `pabbrev scavenging` messages, is there a way to disable those from echoing all the time?

Cheers.

**Comment by amno1** [comment]
Prashant Tak ***@***.***> writes:

> Hi, thanks for the wonderful package, really enjoy using this over popup based completion systems.

All thanks goes to Phillip!

Yes, it is indeed refreshing. I have now implemented a capf for Company/Corfu
users, but I use myself the overlay suggestions.

> I wanted to know if it's possible to change how the overlay appears, I don't want to see the "[" brackets and wanted to know if its possible to

Currently it is not possible, since it is hardcoded as you have seen. But I do
have a plan to add a customize option exactly for this purpose. I just haven't
worked on that one yet. I wanted to do something that involves a bit more work,
and than decorators. But it is comming. In a week or two :).

> change the overlay without having to rewrite the entire pabbrev-insert-suggestion function and overriding the default with an advice,
> is it possible to just advise the overlay-put call?

No, there is no need for advice. 

I meant to introduce a customize options, pabbrev-suggestion-decorators, that
will take a string of two characters, for left and right decorator. I just
haven't done that yet, but it has been on my mind for a couple of weeks already.

> And one more thing is the frequent pabbrev scavenging messages, is there a way to disable those from echoing all the time?

Yes. If you customize pabbrev-idle-timer-verbose to nil, either in your init
file or via customize, it should not print those messages.

Alternatively you can switch them off in the current buffer with M-x
pabbrev-shut-up.

> Cheers.

Best regards
/arthur

**Comment by brongulus** [comment]
> Yes, it is indeed refreshing. I have now implemented a capf for Company/Corfu
users, but I use myself the overlay suggestions.

Oh, can you tell me more about that?

> I meant to introduce a customize options, pabbrev-suggestion-decorators, that
will take a string of two characters, for left and right decorator. I just
haven't done that yet, but it has been on my mind for a couple of weeks already.

Thank you, I'll keep an eye out for that then.

**Comment by amno1** [comment]
Prashant Tak ***@***.***> writes:

>  Yes, it is indeed refreshing. I have now implemented a capf for Company/Corfu
>  users, but I use myself the overlay suggestions.
>
> Oh, can you tell me more about that?

Capf? You can check the development branch here:

https://github.com/amno1/pabbrev/tree/pabbrev-capf

And if you are interesting to try, I have also made a little variation on
suggestion overlay that lets one cycle through the suggestions. The branch is
over here:

https://github.com/amno1/pabbrev/tree/pabbrev-cycle-suggestions

The interaction is somewhat different: tab key cycle amongst suggestions, and
return key inserts the visible suggestion.

I haven't merged those together yet, so you will have to try them separately for
the moment, if you are interested in any.

I'll be happy if I can get some feedback. Both positive and negative are
appreciated.

**Comment by brongulus** [comment]
Oh wow, both of them seem like they'd be considerable QoL improvements.
I'll give those branches a try for sure!

**Comment by amno1** [comment]
Prashant Tak ***@***.***> writes:

> Oh wow, both of them seem like they'd be considerable QoL improvements.
> I'll give those branches a try for sure!

Thank you; would be glad to hear how they work for someone else, and if you find
any problems.

**Comment by brongulus** [comment]
Looks like `pabbrev-capf` already has the tab-cycle behavior so didn't have to switch branches. 
One thing I noticed is that when I actually wish to use `RET` for newline, and it is in between paranthesis,
with pabbrev enabled, it doesn't indent the closing paranthesis and/or add newline as expected but rather just move to the next line.

Let me illustrate for a bit more clarification:
```
fn abc {|} ---> press RET when cursor is at |
```
With pabbrev expands to
```
fn abc {
|}
```

Without pabbrev it expands as:
```
fn abc {
    |
}
```
Also, how do I cancel pabbrev-completion if I don't want to choose any candidate?

**Comment by amno1** [comment]
Prashant Tak ***@***.***> writes:

> Looks like pabbrev-capf already has the tab-cycle behavior so didn't have to switch branches.

It is possible; capf was a small triviality, but I thought I refactored it out
:). I am working on making an option to choose which completion style to use; so
the one will exclude the other. 

> One thing I noticed is that when I actually wish to use RET for newline, and it is in between paranthesis,
> with pabbrev enabled, it doesn't indent the closing paranthesis and/or add newline as expected but rather just move to the next line.
>
> Let me illustrate for a bit more clarification:
> With pabbrev:
>
> fn abc {|} ---> press RET when cursor is at |
>
> expands to
>
> fn abc {
> |}
>
> Without pabbrev it expands as:
>
> fn abc {
>     |
> }

That is interesting to know. I have tried to make it work the same as the tab
key. When there is no active suggestion overlay it should perform whatever it is
normally bount to; but perhaps I have done a bit wrong. I will check it up
again. Thank you.

**Comment by brongulus** [comment]
Maybe binding `pabbrev-expand-maybe` to C-return instead of return might work, otherwise everytime we want to enter a new line and a completion is present, RET will always choose the completion over actually adding a newline.

**Comment by amno1** [comment]
Prashant Tak ***@***.***> writes:

> Maybe binding pabbrev-expand-maybe to C-return instead of return might work, otherwise everytime we want to enter a new line and a
> completion is present, RET will always choose the completion over actually adding a newline.

Yes. I am aware of it, but am not sure what is the best solution. Using ret for
insertion is just an experiment thus far.

Sure, you can test if ctrl + enter works better; but that is a very contested
combo. There are a lots of modes that bind something to RET key and C-return,
M-return etc. It will clash with Org mode for sure.

Did you try M-return? I personally find it a bit hard to type, since I have to
fold in my thumb, but perhaps it works for you?

(define-key pabbrev-mode-map [M-return] #'pabbrev-expand-maybe)

Or perhaps M-return should do the default RET action when there is a pabbrev
suggestion. The idea is to make it fast and easy to confirm at
suggestion.

Thanks for the input.

**Comment by amno1** [comment]
I have now pushed a prototype for customizable overlay decorator; you can check this branch:

https://github.com/amno1/pabbrev/tree/pabbrev-overlay-decorators

In order to be sure the decorator string is correct, I suggest using either customize-set-variable or the new setopt. Just so that :set function is run. Otherwise it should be a string of two chars, chat at index 0 is left decorator and char at index 1 is the right decorator. Must be printable characters. Nil string means no decorators.

**Comment by brongulus** [comment]
There is an issue with nil decorators, the cursor automatically moves to the end of the overlay and doesn't move back on backspace until the overlay goes away.

<img width="578" alt="image" src="https://github.com/phillord/pabbrev/assets/53148859/31338fd1-9e49-4179-b9fa-2d0dc4181740">

Doesn't happen if you give non-nil decorators.

**Comment by amno1** [comment]
I see; empty string of course. There is also a warning. Ok, I think I know how to solve it :).

**Comment by amno1** [comment]
I think it works now; at least for me. But check if you find more bugs. Thanks for help!

**Comment by brongulus** [comment]
Works like a charm now! :)
Thanks.

**Comment by amno1** [comment]
Cool, thanks for help with testing!
