### ISSUE TITLE
Possible bug in `pabbrev-suggestions-subseq`

### ISSUE THREAD

**Issue by sirikid** [phillord/pabbrev#8]
https://github.com/phillord/pabbrev/blob/bf8a498f2ddd268981d43fb71cf98aa2e4be3942/pabbrev.el#L991

Should not it be as follows?
```elisp
 (cl-subseq sequence (max 0 from) (min to (length sequence)))) 
```

**Comment by amno1** [comment]
From can be negative. I don't know if negative indexing is used in pabbrev though, I haven't looked more deeply at that code, but I would assume there is a reason why Phillip wrote it the way he did. Have you tested what values FROM has?

**Comment by phillord** [comment]
Why it is that way, I have no idea, but it is only called twice and `from` is always `zero`.  The parameter is pointless.

**Comment by amno1** [comment]
Alrighty; thanks for the clarification! Perhaps a remnant of some factorization or a test in the past, or compatibility before cl-subseq.

I looked at the code now too.  Are you OK if I remove the pabbrev-suggestions-subseq and just use cl-subseq directly? The interface is the same, but cl-subseq is less to type :).

**Comment by sirikid** [comment]
> Why it is that way, I have no idea, but it is only called twice and `from` is always `zero`. The parameter is pointless.

Well, that is the reason why it's never caused troubles :^)

**Comment by phillord** [comment]
I was curious and checked the history. It has been there since the first checkin which looked like this. So originally, for xemacs support.

```
(defun pabbrev-suggestions-subseq(sequence from to)
  "Return subsequence from seq.
FROM starting here
TO finishing here.
Amazing though it seems the implementation of this differs between Emacs,
and XEmacs. Irritating or what!
The Emacs version copes with numbers past the end, and backs with nil
values. XEmacs uses its own builtin rather than the one in the CL package.
It crashes under the same circumstances. Yeech."
  (if pabbrev-xemacs-p
      (subseq sequence from
	      (min to
		   (length sequence)))
    (subseq sequence from to)))
```


But that does not explain the `max` and `min`. This came in after the move from `subseq` to `cl-subseq` (which are now aliases of each other but may not have been in the past).

```
(defun pabbrev-suggestions-subseq(sequence from to)
  "Return subsequence from seq.
FROM starting here
TO finishing here.
Amazing though it seems the implementation of this differs between Emacs,
and XEmacs. Irritating or what!
The Emacs version copes with numbers past the end, and backs with nil
values. XEmacs uses its own builtin rather than the one in the CL package.
It crashes under the same circumstances. Yeech."
  (if (featurep 'xemacs)
      (subseq sequence from
              (min to
                   (length sequence)))
    (cl-subseq sequence
               (min 0 from)
               (min (length sequence) to))))
```

So that confirms that check on the last form is there for a reason. I probably did `(min 0 from)` at the same time. It is wrong but harmless. But the bounds check on the `to` value is needed or it will crash. So the interface is not the same as `cl-subseq`, even if the parameters are!

**Comment by amno1** [comment]
> The Emacs version copes with numbers past the end, and backs with nil
values. XEmacs uses its own builtin rather than the one in the CL package.
It crashes under the same circumstances.

I think I have seen similar handling for some text property as well. That makes sense now. Thanks.

> the bounds check on the to value is needed or it will crash. So the interface is not the same as cl-subseq, even if the parameters are!

I meant to leave the bounds check. I understand the length can and will be < 10 chars at times. I did that in my private. But I can also just remove the first check and leave FROM and pabbrev-suggestions-subseq in. Honestly, I don't think it matters much, as you say the test is harmless, and I don't think it costs much of CPU time either, mostly for the clarification if someone else might be wondering too. Do you think this one is OK:

```
 (defsubst pabbrev-suggestions-subseq(sequence from to)
-  "Return subsequence from SEQUENCE starting FROM and ending with TO."
-  (cl-subseq sequence (min 0 from) (min (length sequence) to)))
+  "Return subsequence from SEQUENCE starting FROM and ending with TO.
+
+FROM should be zero or a positive integer."
+  (cl-subseq sequence from (min (length sequence) to)))
```

I can also just leave everything as is too :).
